[user]
email = "m@mitchellh.com"
name = "Mitchell Hashimoto"

[signing]
sign-all = true
backend = "gpg"

[aliases]
b = ["branch"]
n = ["new"]

[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"

[ui]
default-command = "log"
