[user]
email = "m@mitchellh.com"
name = "Mitchell Hashimoto"

[signing]
backend = "gpg"
behavior = "own"

[aliases]
b = ["branch"]
n = ["new"]

# Move the closest bookmark to the current commit. This is useful when
# working on a named branch, creating a bunch of commits, and then needing
# to update the bookmark before pushing.
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]

# Rebase the current branch onto the trunk.
retrunk = ["rebase", "-d", "trunk()"]

[revset-aliases]
"closest_bookmark(to)" = "heads(::to & bookmarks())"
"fork_history(to, from)" = "fork_point(to | from)..@"

[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"

[ui]
default-command = "log"
